### ISSUE TITLE
Crashes after inputting file path.

### ISSUE THREAD

**Issue by ryderbr** [noterday/mugen2rivals#1]
Hi. To be simple, whenever I put in the path of the character folder, I see a flash of code and then it just crashes. I have both pillow and python3 installed and have tried running it with administrator mode. I can find the output folder, but nothing is in there.

**Comment by noterday** [comment]
Hi, I honestly haven't looked at this project in about a year. Could you link me what character you were using so I can test it myself?

**Comment by ryderbr** [comment]
https://mugenarchive.com/forums/downloads.php?do=file&id=148384-gojo-satoru-joey-jostar&__cf_chl_jschl_tk__=bfd1c6552b812ac50b26772450c54780d051c094-1618792855-0-ASDrp4wrK7smOAD8a6e-vgUjarkLMlpXeWJb899TOinoYXArQ7oMidMXUC-jMPXWZzu2TlGT8z7-7ER7hyBh63IP7U31n13LJ1kH1XknO_We8pKUJncMwZLlNqWOYtO5HWuw240zdls4zQDERIp1N9Pmd4dj6VCI1RDmBguTKsuHlhgGNbskGG6LC5cMdBSET2hbOpM_6AIACkcfcGoAlCEV-osdfY-HcgzTeUcP5Zbcn7M28BwkzhUY93rBd1WdNh7Ey3kQqHivz7O_gHFj9Vfp9Ts1upcBv1FIB2GWNv6kU6CEUL9TTrfcESQRVZIfAR6t7R0OPqlAFSO7Ope2nCn7eJ1Tx_QvXuy-VzWNBbizk57P7IC4JVqfrJFeJHAVmBPa9qWxO8yW-riJwC8RCS9UVVhkcEsaVJBbereBIG2FXEXZnJn462EdldhcIYjfAKXY8fBsOxk6SdEDms2ybF8

**Comment by ryderbr** [comment]
any luck?

**Comment by noterday** [comment]
Apologies for the long wait. I couldn't take a look at this project until now.

This issue was caused by outdated Mugen dev tools being used to convert files. I put up a new release that should be compatible with newer Mugen projects. I was able to convert the character you linked using it.
